Replace mirror.yandex.ru/debian with archive.debian.org/debian
As https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html
wheezy is removed from debian archive and its mirror.

This cause all tests failed, like

ERROR: unable to fetch mirror: HTTP code 404 while fetching
http://mirror.yandex.ru/debian/dists/wheezy/Release

And http://archive.debian.org/debian/dists/wheezy/non-free/debian-installer
is 404